# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\深海\截流板\controller\connect.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(317, 173)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.ip_adresses = QtWidgets.QLineEdit(Form)
        self.ip_adresses.setGeometry(QtCore.QRect(120, 20, 161, 30))
        self.ip_adresses.setObjectName("ip_adresses")
        self.ip_port = QtWidgets.QLineEdit(Form)
        self.ip_port.setGeometry(QtCore.QRect(120, 60, 161, 30))
        self.ip_port.setObjectName("ip_port")
        self.ping_btn = QtWidgets.QPushButton(Form)
        self.ping_btn.setGeometry(QtCore.QRect(30, 110, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ping_btn.setFont(font)
        self.ping_btn.setObjectName("ping_btn")
        self.connect_btn = QtWidgets.QPushButton(Form)
        self.connect_btn.setGeometry(QtCore.QRect(160, 110, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.connect_btn.setFont(font)
        self.connect_btn.setObjectName("connect_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "连接PLC"))
        self.label.setText(_translate("Form", "地址"))
        self.label_2.setText(_translate("Form", "端口号"))
        self.ping_btn.setText(_translate("Form", "测试通信"))
        self.connect_btn.setText(_translate("Form", "连接"))
